//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Art
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Art()
        {
            this.Carts = new HashSet<Cart>();
            this.favourite_Arts = new HashSet<favourite_Arts>();
            this.Auctions = new HashSet<Auction>();
            this.Customer_Gallery_Items = new HashSet<Customer_Gallery_Items>();
            this.order_details = new HashSet<order_details>();
            this.Art_exhibition = new HashSet<Art_exhibition>();
            this.Art_Views = new HashSet<Art_Views>();
            this.Art_Comment = new HashSet<Art_Comment>();
        }
    
        public int art_id { get; set; }
        public string art_name { get; set; }
        public int art_price { get; set; }
        public string art_description { get; set; }
        public string art_dateOfCreation { get; set; }
        public Nullable<int> art_fk_ar { get; set; }
        public Nullable<int> Art_fk_soA_id { get; set; }
        public string art_image { get; set; }
        public Nullable<int> art_status { get; set; }
        public Nullable<int> art_fk_cat { get; set; }
        public Nullable<bool> art_isAuction { get; set; }
        public Nullable<int> art_buy_status { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Category Category { get; set; }
        public virtual Style_of_Art Style_of_Art { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favourite_Arts> favourite_Arts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auction> Auctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Gallery_Items> Customer_Gallery_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Art_exhibition> Art_exhibition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Art_Views> Art_Views { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Art_Comment> Art_Comment { get; set; }
    }
}
