//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Art_Comment
    {
        public int ac_id { get; set; }
        public string ac_text { get; set; }
        public string ac_time_stamp { get; set; }
        public Nullable<int> ac_fk_cus_id { get; set; }
        public Nullable<int> ac_fk_art_id { get; set; }
    
        public virtual Art Art { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
