//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artist()
        {
            this.Arts = new HashSet<Art>();
        }
    
        public int ar_id { get; set; }
        public string ar_firstName { get; set; }
        public string ar_lastName { get; set; }
        public string ar_dateOfBirth { get; set; }
        public string ar_country { get; set; }
        public string ar_city { get; set; }
        public string ar_phone { get; set; }
        public Nullable<int> ar_fk_cat { get; set; }
        public string ar_image { get; set; }
        public string ar_email { get; set; }
        public string ar_userName { get; set; }
        public string ar_password { get; set; }
        public string ar_confrim_pass { get; set; }
        public Nullable<decimal> Vault { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Art> Arts { get; set; }
        public virtual Category Category { get; set; }
    }
}
