//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auction()
        {
            this.Bids = new HashSet<Bid>();
        }
    
        public int auc_id { get; set; }
        public string auc_item { get; set; }
        public string auc_start_date { get; set; }
        public string auc_end_date { get; set; }
        public int auc_amount { get; set; }
        public Nullable<long> auc_increment { get; set; }
        public int auc_status { get; set; }
        public Nullable<int> auc_fk_art { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual Art Art { get; set; }
    }
}
