//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        public int bid_id { get; set; }
        public Nullable<int> bid_fk_cus { get; set; }
        public Nullable<long> bid_amount { get; set; }
        public string bid_timeStamp { get; set; }
        public Nullable<int> bid_fk_auc { get; set; }
    
        public virtual Auction Auction { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
