//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int car_id { get; set; }
        public int art_id { get; set; }
        public int cus_id { get; set; }
    
        public virtual Art Art { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
