//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int ci_id { get; set; }
        public string ci_name { get; set; }
        public Nullable<int> ci_fk_con_id { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
