//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGallery.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_ArtGalleryEntities : DbContext
    {
        public db_ArtGalleryEntities()
            : base("name=db_ArtGalleryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Art> Arts { get; set; }
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Style_of_Art> Style_of_Art { get; set; }
        public virtual DbSet<favourite_Arts> favourite_Arts { get; set; }
        public virtual DbSet<Auction> Auctions { get; set; }
        public virtual DbSet<Bid> Bids { get; set; }
        public virtual DbSet<Customer_Gallery> Customer_Gallery { get; set; }
        public virtual DbSet<Customer_Gallery_Items> Customer_Gallery_Items { get; set; }
        public virtual DbSet<order_details> order_details { get; set; }
        public virtual DbSet<Art_exhibition> Art_exhibition { get; set; }
        public virtual DbSet<Exhibition> Exhibitions { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<Website_fund> Website_fund { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<Art_Views> Art_Views { get; set; }
        public virtual DbSet<Art_Comment> Art_Comment { get; set; }
    }
}
