//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Website_fund
    {
        public int f_id { get; set; }
        public string f_date { get; set; }
        public Nullable<decimal> f_amount { get; set; }
        public Nullable<int> f_fk_c_id { get; set; }
        public Nullable<int> f_fk_o_id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual order order { get; set; }
    }
}
